---
updates:
  - directory: /
    groups:
      dev-dependencies:
        dependency-type: development
      production-dependencies:
        dependency-type: production
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
